### ISSUE TITLE
Missing maven artifact 

### ISSUE THREAD

**Issue by bladecatcher** [arteam/jdit#1]
Maven complains of `Missing artifact com.github.arteam:jdit:jar: 0.5` when this dependency is added.

**Comment by arteam** [comment]
Hi @bladecatcher, 

Sorry about that. The library is not published to the Maven Central repository, only to JCenter. I've been always publishing my personal projects there, because of a more simple publishing process. But it looks like project has gained enough traction to publish it Maven Central as well. I will try to get my hands on it. For the time being, you can instruct Maven to look for the project in the JCenter repository with the following declaration in your pom file:
```xml
<repositories>
        <repository>
            <id>jcenter</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
</repositories>
```

Thanks for your interest in jdit!

**Comment by arteam** [comment]
The version 0.5 has been [published](http://search.maven.org/#artifactdetails%7Ccom.github.arteam%7Cjdit%7C0.5%7Cjar) to the Maven Central repository.
